### ISSUE TITLE
lora微调后启动失败:AttributeError: module 'triton.language.extra.cuda' has no attribute 'gdc_wait'

### ISSUE THREAD

**Issue by fresher1chen** [a710128/nanovllm-voxcpm#60]
环境配置：
nano-vllm-voxcpm          2.0.2
triton                    3.1.0
torch                     2.5.1+cu124
torch-complex             0.4.4
torchaudio                2.5.1+cu124
torchcodec                0.13.0
torchvision               0.20.1+cu124
nvidia-cublas             13.1.1.3
nvidia-cublas-cu12        12.4.5.8
nvidia-cuda-cupti         13.0.85
nvidia-cuda-cupti-cu12    12.4.127
nvidia-cuda-nvrtc         13.0.88
nvidia-cuda-nvrtc-cu12    12.4.127
nvidia-cuda-runtime       13.0.96
nvidia-cuda-runtime-cu12  12.4.127
nvidia-cudnn-cu12         9.1.0.70
nvidia-cudnn-cu13         9.20.0.48
nvidia-cufft              12.0.0.61
nvidia-cufft-cu12         11.2.1.3
nvidia-cufile             1.15.1.6
nvidia-curand             10.4.0.35
nvidia-curand-cu12        10.3.5.147
nvidia-cusolver           12.0.4.66
nvidia-cusolver-cu12      11.6.1.9
nvidia-cusparse           12.6.3.3
nvidia-cusparse-cu12      12.3.1.170
nvidia-cusparselt-cu13    0.8.1
nvidia-nccl-cu12          2.21.5
nvidia-nccl-cu13          2.29.7
nvidia-nvjitlink          13.0.88
nvidia-nvjitlink-cu12     12.4.127
nvidia-nvshmem-cu13       3.4.5
nvidia-nvtx               13.0.85
nvidia-nvtx-cu12          12.4.127
voxcpm                    2.0.3
启动命令
NANOVLLM_LORA_ENABLED=true NANOVLLM_SERVERPOOL_GPU_MEMORY_UTILIZATION=0.8 NANOVLLM_SERVERPOOL_DEVICES=1 fastapi run app/main.py --host 0.0.0.0 --port 8001
报错：
   FastAPI   Starting production server 🚀
 
             Searching for package file structure from directories with __init__.py files
             Importing from /data/chen/lora_voxcpm/nanovllm-voxcpm-2.0.2/deployment
 
    module   📁 app            
             ├── 🐍 __init__.py
             └── 🐍 main.py    
 
      code   Importing the FastAPI app object from the module with the following code:
 
             from app.main import app
 
       app   Using import string: app.main:app
 
    server   Server started at http://0.0.0.0:8001
    server   Documentation at http://0.0.0.0:8001/docs
 
             Logs:
 
      INFO   Started server process [3667146]
      INFO   Waiting for application startup.
/data/chen/lora_voxcpm/.venv/lib/python3.11/site-packages/torch/nn/utils/weight_norm.py:143: FutureWarning: `torch.nn.utils.weight_norm` is deprecated in favor of `torch.nn.utils.parametrizations.weight_norm`.
  WeightNorm.apply(module, name, dim)
/data/chen/lora_voxcpm/.venv/lib/python3.11/site-packages/nanovllm_voxcpm/models/voxcpm2/runner.py:54: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  vae_state_dict = torch.load(os.path.join(model_path, "audiovae.pth"))["state_dict"]
[rank0]:[W525 19:20:04.002694243 ProcessGroupNCCL.cpp:1250] Warning: WARNING: process group has NOT been destroyed before we destruct ProcessGroupNCCL. On normal program exit, the application should call destroy_process_group to ensure that any pending NCCL operations have finished in this process. In rare cases this process can exit before this point and block the progress of another member of the process group. This constraint has always been present,  but this warning has only been added since PyTorch 2.4 (function operator())
     ERROR   Traceback (most recent call last):                                                                                                                       
               File "/data/chen/lora_voxcpm/.venv/lib/python3.11/site-packages/starlette/routing.py", line 638, in lifespan                                    
                 async with self.lifespan_context(app) as maybe_state:                                                                                                
               File "/home/appgroup/.local/share/uv/python/cpython-3.11.15-linux-x86_64-gnu/lib/python3.11/contextlib.py", line 210, in __aenter__                    
                 return await anext(self.gen)                                                                                                                         
                        ^^^^^^^^^^^^^^^^^^^^^                                                                                                                         
               File "/data/chen/lora_voxcpm/.venv/lib/python3.11/site-packages/fastapi/routing.py", line 216, in merged_lifespan                               
                 async with original_context(app) as maybe_original_state:                                                                                            
               File "/home/appgroup/.local/share/uv/python/cpython-3.11.15-linux-x86_64-gnu/lib/python3.11/contextlib.py", line 210, in __aenter__                    
                 return await anext(self.gen)                                                                                                                         
                        ^^^^^^^^^^^^^^^^^^^^^                                                                                                                         
               File "/data/chen/lora_voxcpm/nanovllm-voxcpm-2.0.2/deployment/app/core/lifespan.py", line 57, in lifespan                                       
                 await server.wait_for_ready()                                                                                                                        
               File "/data/chen/lora_voxcpm/.venv/lib/python3.11/site-packages/nanovllm_voxcpm/models/voxcpm2/server.py", line 501, in wait_for_ready          
                 await asyncio.gather(*)                                                                                                                              
               File "/data/chen/lora_voxcpm/.venv/lib/python3.11/site-packages/nanovllm_voxcpm/models/voxcpm2/server.py", line 380, in wait_for_ready          
                 await self._init_fut                                                                                                                                 
             RuntimeError: Traceback (most recent call last):                                                                                                         
               File "/data/chen/lora_voxcpm/.venv/lib/python3.11/site-packages/nanovllm_voxcpm/models/voxcpm2/server.py", line 200, in main_loop               
                 srv = VoxCPM2ServerImpl(*args, **kwargs)                                                                                                             
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                             
               File "/data/chen/lora_voxcpm/.venv/lib/python3.11/site-packages/nanovllm_voxcpm/models/voxcpm2/server.py", line 86, in __init__                 
                 self.llm = VoxCPM2Engine(engine_config)                                                                                                              
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                              
               File "/data/chen/lora_voxcpm/.venv/lib/python3.11/site-packages/nanovllm_voxcpm/models/voxcpm2/engine.py", line 40, in __init__                 
                 super().__init__(VoxCPM2Runner, config, config.tensor_parallel_size)                                                                                 
               File "/data/chen/lora_voxcpm/.venv/lib/python3.11/site-packages/nanovllm_voxcpm/engine/llm_engine.py", line 117, in __init__                    
                 self.model_runner = RunnerType(config, 0, config.devices[0], self.distributed_port, self.events)                                                     
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                     
               File "/data/chen/lora_voxcpm/.venv/lib/python3.11/site-packages/nanovllm_voxcpm/models/voxcpm2/runner.py", line 42, in __init__                 
                 super().__init__(config, rank, device_idx, distributed_port, event)                                                                                  
               File "/data/chen/lora_voxcpm/.venv/lib/python3.11/site-packages/nanovllm_voxcpm/engine/model_runner.py", line 230, in __init__                  
                 self.capture_cudagraph()                                                                                                                             
               File "/data/chen/lora_voxcpm/.venv/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context                      
                 return func(*args, **kwargs)                                                                                                                         
                        ^^^^^^^^^^^^^^^^^^^^^                                                                                                                         
               File "/data/chen/lora_voxcpm/.venv/lib/python3.11/site-packages/nanovllm_voxcpm/engine/model_runner.py", line 856, in capture_cudagraph         
                 assign_outputs(self.model(**cut_inputs(inputs, bs)), outputs, bs)                                                                                    
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                  
               File "/data/chen/lora_voxcpm/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl                   
                 return self._call_impl(*args, **kwargs)                                                                                                              
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                              
               File "/data/chen/lora_voxcpm/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl                           
                 return forward_call(*args, **kwargs)                                                                                                                 
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                 
               File "/data/chen/lora_voxcpm/.venv/lib/python3.11/site-packages/nanovllm_voxcpm/models/voxcpm2/model.py", line 640, in forward                  
                 feat_embeds = self.enc_to_lm_proj(self.feat_encoder(feat))                                                                                           
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                           
               File "/data/chen/lora_voxcpm/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl                   
                 return self._call_impl(*args, **kwargs)                                                                                                              
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                              
               File "/data/chen/lora_voxcpm/.venv/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl                           
                 return forward_call(*args, **kwargs)                                                                                                                 
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                 
               File "/data/chen/lora_voxcpm/.venv/lib/python3.11/site-packages/nanovllm_voxcpm/layers/lora.py", line 849, in forward                           
                 y_flat = backend.add_lora(                                                                                                                           
                          ^^^^^^^^^^^^^^^^^                                                                                                                           
               File "/data/chen/lora_voxcpm/.venv/lib/python3.11/site-packages/nanovllm_voxcpm/lora.py", line 319, in add_lora                                 
                 lora_expand(                                                                                                                                         
               File "/data/chen/lora_voxcpm/.venv/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context                      
                 return func(*args, **kwargs)                                                                                                                         
                        ^^^^^^^^^^^^^^^^^^^^^                                                                                                                         
               File "/data/chen/lora_voxcpm/.venv/lib/python3.11/site-packages/nanovllm_voxcpm/lora_ops/triton_ops/lora_expand_op.py", line 137, in lora_expand
                 _lora_expand_kernel(                                                                                                                                 
               File "/data/chen/lora_voxcpm/.venv/lib/python3.11/site-packages/triton/runtime/jit.py", line 345, in <lambda>                                   
                 return lambda *args, **kwargs: self.run(grid=grid, warmup=False, *args, **kwargs)                                                                    
                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                    
               File "/data/chen/lora_voxcpm/.venv/lib/python3.11/site-packages/triton/runtime/jit.py", line 662, in run                                        
                 kernel = self.compile(                                                                                                                               
                          ^^^^^^^^^^^^^                                                                                                                               
               File "/data/chen/lora_voxcpm/.venv/lib/python3.11/site-packages/triton/compiler/compiler.py", line 240, in compile                              
                 key = f"{triton_key()}-{src.hash()}-{backend.hash()}-{options.hash()}-{str(sorted(env_vars.items()))}"                                               
                                         ^^^^^^^^^^                                                                                                                   
               File "/data/chen/lora_voxcpm/.venv/lib/python3.11/site-packages/triton/compiler/compiler.py", line 109, in hash                                 
                 key = f"{self.fn.cache_key}-{self.attrs.hash()}-{sorted_sig}-{sorted_constants}"                                                                     
                          ^^^^^^^^^^^^^^^^^                                                                                                                           
               File "/data/chen/lora_voxcpm/.venv/lib/python3.11/site-packages/triton/runtime/jit.py", line 758, in cache_key                                  
                 dependencies_finder.visit(self.parse())                                                                                                              
               File "/home/appgroup/.local/share/uv/python/cpython-3.11.15-linux-x86_64-gnu/lib/python3.11/ast.py", line 418, in visit                                
                 return visitor(node)                                                                                                                                 
                        ^^^^^^^^^^^^^                                                                                                                                 
               File "/home/appgroup/.local/share/uv/python/cpython-3.11.15-linux-x86_64-gnu/lib/python3.11/ast.py", line 426, in generic_visit                        
                 self.visit(item)                                                                                                                                     
               File "/home/appgroup/.local/share/uv/python/cpython-3.11.15-linux-x86_64-gnu/lib/python3.11/ast.py", line 418, in visit                                
                 return visitor(node)                                                                                                                                 
                        ^^^^^^^^^^^^^                                                                                                                                 
               File "/data/chen/lora_voxcpm/.venv/lib/python3.11/site-packages/triton/runtime/jit.py", line 167, in visit_FunctionDef                          
                 self.generic_visit(node)                                                                                                                             
               File "/home/appgroup/.local/share/uv/python/cpython-3.11.15-linux-x86_64-gnu/lib/python3.11/ast.py", line 426, in generic_visit                        
                 self.visit(item)                                                                                                                                     
               File "/home/appgroup/.local/share/uv/python/cpython-3.11.15-linux-x86_64-gnu/lib/python3.11/ast.py", line 418, in visit                                
                 return visitor(node)                                                                                                                                 
                        ^^^^^^^^^^^^^                                                                                                                                 
               File "/home/appgroup/.local/share/uv/python/cpython-3.11.15-linux-x86_64-gnu/lib/python3.11/ast.py", line 428, in generic_visit                        
                 self.visit(value)                                                                                                                                    
               File "/home/appgroup/.local/share/uv/python/cpython-3.11.15-linux-x86_64-gnu/lib/python3.11/ast.py", line 418, in visit                                
                 return visitor(node)                                                                                                                                 
                        ^^^^^^^^^^^^^                                                                                                                                 
               File "/data/chen/lora_voxcpm/.venv/lib/python3.11/site-packages/triton/runtime/jit.py", line 144, in visit_Call                                 
                 func_cache_key = obj.cache_key                                                                                                                       
                                  ^^^^^^^^^^^^^                                                                                                                       
               File "/data/chen/lora_voxcpm/.venv/lib/python3.11/site-packages/triton/runtime/jit.py", line 758, in cache_key                                  
                 dependencies_finder.visit(self.parse())                                                                                                              
               File "/home/appgroup/.local/share/uv/python/cpython-3.11.15-linux-x86_64-gnu/lib/python3.11/ast.py", line 418, in visit                                
                 return visitor(node)                                                                                                                                 
                        ^^^^^^^^^^^^^                                                                                                                                 
               File "/home/appgroup/.local/share/uv/python/cpython-3.11.15-linux-x86_64-gnu/lib/python3.11/ast.py", line 426, in generic_visit                        
                 self.visit(item)                                                                                                                                     
               File "/home/appgroup/.local/share/uv/python/cpython-3.11.15-linux-x86_64-gnu/lib/python3.11/ast.py", line 418, in visit                                
                 return visitor(node)                                                                                                                                 
                        ^^^^^^^^^^^^^                                                                                                                                 
               File "/data/chen/lora_voxcpm/.venv/lib/python3.11/site-packages/triton/runtime/jit.py", line 167, in visit_FunctionDef                          
                 self.generic_visit(node)                                                                                                                             
               File "/home/appgroup/.local/share/uv/python/cpython-3.11.15-linux-x86_64-gnu/lib/python3.11/ast.py", line 426, in generic_visit                        
                 self.visit(item)                                                                                                                                     
               File "/home/appgroup/.local/share/uv/python/cpython-3.11.15-linux-x86_64-gnu/lib/python3.11/ast.py", line 418, in visit                                
                 return visitor(node)                                                                                                                                 
                        ^^^^^^^^^^^^^                                                                                                                                 
               File "/data/chen/lora_voxcpm/.venv/lib/python3.11/site-packages/triton/runtime/jit.py", line 221, in visit_Assign                               
                 self.generic_visit(node)                                                                                                                             
               File "/home/appgroup/.local/share/uv/python/cpython-3.11.15-linux-x86_64-gnu/lib/python3.11/ast.py", line 428, in generic_visit                        
                 self.visit(value)                                                                                                                                    
               File "/home/appgroup/.local/share/uv/python/cpython-3.11.15-linux-x86_64-gnu/lib/python3.11/ast.py", line 418, in visit                                
                 return visitor(node)                                                                                                                                 
                        ^^^^^^^^^^^^^                                                                                                                                 
               File "/data/chen/lora_voxcpm/.venv/lib/python3.11/site-packages/triton/runtime/jit.py", line 144, in visit_Call                                 
                 func_cache_key = obj.cache_key                                                                                                                       
                                  ^^^^^^^^^^^^^                                                                                                                       
               File "/data/chen/lora_voxcpm/.venv/lib/python3.11/site-packages/triton/runtime/jit.py", line 758, in cache_key                                  
                 dependencies_finder.visit(self.parse())                                                                                                              
               File "/home/appgroup/.local/share/uv/python/cpython-3.11.15-linux-x86_64-gnu/lib/python3.11/ast.py", line 418, in visit                                
                 return visitor(node)                                                                                                                                 
                        ^^^^^^^^^^^^^                                                                                                                                 
               File "/home/appgroup/.local/share/uv/python/cpython-3.11.15-linux-x86_64-gnu/lib/python3.11/ast.py", line 426, in generic_visit                        
                 self.visit(item)                                                                                                                                     
               File "/home/appgroup/.local/share/uv/python/cpython-3.11.15-linux-x86_64-gnu/lib/python3.11/ast.py", line 418, in visit                                
                 return visitor(node)                                                                                                                                 
                        ^^^^^^^^^^^^^                                                                                                                                 
               File "/data/chen/lora_voxcpm/.venv/lib/python3.11/site-packages/triton/runtime/jit.py", line 167, in visit_FunctionDef                          
                 self.generic_visit(node)                                                                                                                             
               File "/home/appgroup/.local/share/uv/python/cpython-3.11.15-linux-x86_64-gnu/lib/python3.11/ast.py", line 426, in generic_visit                        
                 self.visit(item)                                                                                                                                     
               File "/home/appgroup/.local/share/uv/python/cpython-3.11.15-linux-x86_64-gnu/lib/python3.11/ast.py", line 418, in visit                                
                 return visitor(node)                                                                                                                                 
                        ^^^^^^^^^^^^^                                                                                                                                 
               File "/data/chen/lora_voxcpm/.venv/lib/python3.11/site-packages/triton/runtime/jit.py", line 233, in visit_For                                  
                 self.generic_visit(node)                                                                                                                             
               File "/home/appgroup/.local/share/uv/python/cpython-3.11.15-linux-x86_64-gnu/lib/python3.11/ast.py", line 426, in generic_visit                        
                 self.visit(item)                                                                                                                                     
               File "/home/appgroup/.local/share/uv/python/cpython-3.11.15-linux-x86_64-gnu/lib/python3.11/ast.py", line 418, in visit                                
                 return visitor(node)                                                                                                                                 
                        ^^^^^^^^^^^^^                                                                                                                                 
               File "/home/appgroup/.local/share/uv/python/cpython-3.11.15-linux-x86_64-gnu/lib/python3.11/ast.py", line 426, in generic_visit                        
                 self.visit(item)                                                                                                                                     
               File "/home/appgroup/.local/share/uv/python/cpython-3.11.15-linux-x86_64-gnu/lib/python3.11/ast.py", line 418, in visit                                
                 return visitor(node)                                                                                                                                 
                        ^^^^^^^^^^^^^                                                                                                                                 
               File "/home/appgroup/.local/share/uv/python/cpython-3.11.15-linux-x86_64-gnu/lib/python3.11/ast.py", line 426, in generic_visit                        
                 self.visit(item)                                                                                                                                     
               File "/home/appgroup/.local/share/uv/python/cpython-3.11.15-linux-x86_64-gnu/lib/python3.11/ast.py", line 418, in visit                                
                 return visitor(node)                                                                                                                                 
                        ^^^^^^^^^^^^^                                                                                                                                 
               File "/home/appgroup/.local/share/uv/python/cpython-3.11.15-linux-x86_64-gnu/lib/python3.11/ast.py", line 428, in generic_visit                        
                 self.visit(value)                                                                                                                                    
               File "/home/appgroup/.local/share/uv/python/cpython-3.11.15-linux-x86_64-gnu/lib/python3.11/ast.py", line 418, in visit                                
                 return visitor(node)                                                                                                                                 
                        ^^^^^^^^^^^^^                                                                                                                                 
               File "/data/chen/lora_voxcpm/.venv/lib/python3.11/site-packages/triton/runtime/jit.py", line 127, in visit_Call                                 
                 func = self.visit(node.func)                                                                                                                         
                        ^^^^^^^^^^^^^^^^^^^^^                                                                                                                         
               File "/home/appgroup/.local/share/uv/python/cpython-3.11.15-linux-x86_64-gnu/lib/python3.11/ast.py", line 418, in visit                                
                 return visitor(node)                                                                                                                                 
                        ^^^^^^^^^^^^^                                                                                                                                 
               File "/data/chen/lora_voxcpm/.venv/lib/python3.11/site-packages/triton/runtime/jit.py", line 117, in visit_Attribute                            
                 return getattr(lhs, node.attr)                                                                                                                       
                        ^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                       
             AttributeError: module 'triton.language.extra.cuda' has no attribute 'gdc_wait'
     ERROR   Application startup failed. Exiting.

**Comment by a710128** [comment]
Thanks for the detailed report and environment information.

This specific error is caused by a Triton compatibility issue. The LoRA Triton kernels reference `tl.extra.cuda.gdc_wait` / `gdc_launch_dependents`, but these APIs are not available in Triton 3.1.0. Since PyTorch 2.5.1 commonly comes with Triton 3.1.0, this stack can fail during LoRA kernel JIT compilation with:

```text
AttributeError: module 'triton.language.extra.cuda' has no attribute 'gdc_wait'
```

Upgrading can resolve this particular error, but I recommend upgrading the PyTorch + Triton stack together rather than force-upgrading Triton alone under PyTorch 2.5.1. A Triton version that includes these APIs, such as Triton >= 3.4.0, should avoid this specific failure.

If you need to stay on `torch==2.5.1` / `triton==3.1.0`, then this needs a code-side compatibility fix so the old Triton version does not reference the PDL/GDC APIs at all.

**Comment by fresher1chen** [comment]
👍 torch==2.8.0+cu126   triton==3.4.0 解决了
